Repository dohooo/react-native-reanimated-carousel, pull requests merged in 2022-01, with the labels that each got.

#78 fix: onProgressChange/onSnapToItem props wrong calculation
  src/Carousel.tsx
  src/constants/index.ts
Labels: bug

#80 refactor: refactor useAutoPlay hooks
  example/src/components/SBImageItem.tsx
  example/src/normal/index.tsx
  src/Carousel.tsx
  src/hooks/useAutoPlay.ts
Labels: refactor

#82 docs: update README
  README.md
  README.zh-CN.md
Labels: documentation

#86 refactor: refactor all
  README.md
  README.zh-CN.md
  example/src/stack/index.tsx
  src/Carousel.tsx
  src/hooks/useInitProps.ts
  src/hooks/useLayoutConfig.ts
  src/hooks/useOffsetX.ts
  src/hooks/usePropsErrorBoundary.ts
  src/layouts/BaseLayout.tsx
  src/layouts/NormalLayout.tsx
  src/layouts/ParallaxLayout.tsx
  src/layouts/StackLayout.tsx
  src/layouts/index.tsx
  src/layouts/parallax.ts
  src/layouts/stack.ts
  src/types.ts
Labels: refactor

#87 refactor: create store for carousel
  example/src/parallax/index.tsx
  src/Carousel.tsx
  src/ScrollViewGesture.tsx
  src/hooks/useCarouselController.tsx
  src/hooks/useCommonVariables.ts
  src/hooks/useIndexController.ts
  src/hooks/useInitProps.ts
  src/hooks/useLayoutConfig.ts
  src/hooks/useOnProgressChange.ts
  src/layouts/BaseLayout.tsx
  src/layouts/parallax.ts
  src/layouts/stack.ts
  src/store/index.ts
  src/types.ts
Labels: refactor

#83 refactor: abstract carousel item and layout
  README.md
  README.zh-CN.md
  example/.env
  example/app.config.js
  example/app.json
  example/babel.config.js
  example/package.json
  example/src/components/SBImageItem.tsx
  example/src/components/SBItem.tsx
  example/src/components/SBTextItem.tsx
  example/src/components/SButton.tsx
  example/src/contant/index.ts
  example/src/normal/index.tsx
  example/src/parallax/index.tsx
  example/src/snap-carousel-loop/index.tsx
  example/src/stack/index.tsx
  example/yarn.lock
  src/Carousel.tsx
  src/ScrollViewGesture.tsx
  src/hooks/useCarouselController.tsx
  src/hooks/useCommonVariables.ts
  src/hooks/useIndexController.ts
  src/hooks/useInitProps.ts
  src/hooks/useLayoutConfig.ts
  src/hooks/useOffsetX.ts
  src/hooks/useOnProgressChange.ts
  src/hooks/usePropsErrorBoundary.ts
  src/layouts/BaseLayout.tsx
  src/layouts/StackLayout.tsx
  src/layouts/index.tsx
  src/layouts/normal.ts
  src/layouts/parallax.ts
  src/layouts/stack.ts
  src/store/index.ts
  src/types.ts
Labels: refactor

#90 feat: pass animation value to renderItem
  README.md
  README.zh-CN.md
  assets/advanced-parallax.gif
  assets/scale-fade-in-out.gif
  docs/custom-animation.md
  docs/custom-animation.zh-CN.md
  docs/props.md
  docs/props.zh-CN.md
  example/src/advanced-parallax/index.tsx
  example/src/complex/index.tsx
  example/src/components/SBImageItem.tsx
  example/src/components/SBItem.tsx
  example/src/components/SBTextItem.tsx
  example/src/home/index.tsx
  example/src/index.tsx
  example/src/normal/index.tsx
  example/src/parallax/index.tsx
  example/src/scale-fade-in-out/index.tsx
  example/src/stack/index.tsx
  package.json
  src/Carousel.tsx
  src/layouts/BaseLayout.tsx
  src/types.ts
Labels: enhancement

#91 Feat/custom animation
  README.md
  README.zh-CN.md
  assets/advanced-parallax.gif
  assets/scale-fade-in-out.gif
  docs/custom-animation.md
  docs/custom-animation.zh-CN.md
  docs/props.md
  docs/props.zh-CN.md
  example/package.json
  example/src/advanced-parallax/index.tsx
  example/src/complex/index.tsx
  example/src/components/SBImageItem.tsx
  example/src/components/SBItem.tsx
  example/src/components/SBTextItem.tsx
  example/src/home/index.tsx
  example/src/index.tsx
  example/src/normal/index.tsx
  example/src/parallax/index.tsx
  example/src/scale-fade-in-out/index.tsx
  example/src/stack/index.tsx
  package.json
  src/Carousel.tsx
  src/hooks/useInitProps.ts
  src/layouts/BaseLayout.tsx
  src/layouts/parallax.ts
  src/layouts/stack.ts
  src/types.ts
Labels: enhancement

#92 docs: update custom-animation.md
  assets/custom-animation-sketch.png
  docs/custom-animation.md
  docs/custom-animation.zh-CN.md
  stack-horizontal-right.gif
Labels: documentation

#93 autoplay will scroll out of bounds
  src/Carousel.tsx
  src/ScrollViewGesture.tsx
  src/constants/index.ts
  src/hooks/useCarouselController.tsx
Labels: bug

#102 fix: fix useCarouselController
  docs/props.md
  docs/props.zh-CN.md
  example/src/advanced-parallax/index.tsx
  example/src/anim-tab-bar/index.tsx
  example/src/hooks/useToggleButton.tsx
  example/src/normal/index.tsx
  example/src/pause-advanced-parallax/index.tsx
  src/Carousel.tsx
  src/ScrollViewGesture.tsx
  src/hooks/useAutoPlay.ts
  src/hooks/useCarouselController.tsx
  src/hooks/useIndexController.ts
  src/hooks/useInitProps.ts
  src/types.ts
Labels: bug, documentation, enhancement

#116 Fix/autoplay error
  CHANGELOG.md
  package.json
  src/Carousel.tsx
  src/ScrollViewGesture.tsx
  src/hooks/useAutoPlay.ts
Labels: bug
