Repository dohooo/react-native-reanimated-carousel, pull requests merged in 2024-05, with the labels that each got.

#597 Feat/paginator
  .changeset/lazy-ties-design.md
  .eslintrc
  .eslintrc.js
  .prettierrc
  example/app/.eslintrc
  example/app/src/__snapshots__/snapshots.test.tsx.snap
  example/app/src/pages/anim-tab-bar/index.tsx
  example/app/src/pages/parallax/index.tsx
  example/website/pages/Examples/anim-tab-bar.mdx
  example/website/pages/props.mdx
  example/website/pages/usage.mdx
  package.json
  src/components/Carousel.tsx
  src/components/Pagination/Basic/PaginationItem.tsx
  src/components/Pagination/Basic/index.tsx
  src/components/Pagination/index.tsx
  src/hooks/useOnProgressChange.ts
  src/index.tsx
  src/types.ts
  yarn.lock
Labels: size:XL

#598 [feat] Adds Pagination component
  .changeset/lazy-ties-design.md
  .eslintrc
  .eslintrc.js
  .prettierrc
  example/app/.eslintrc
  example/app/src/__snapshots__/snapshots.test.tsx.snap
  example/app/src/pages/anim-tab-bar/index.tsx
  example/app/src/pages/parallax/index.tsx
  example/website/pages/Examples/anim-tab-bar.mdx
  example/website/pages/props.mdx
  example/website/pages/usage.mdx
  example/website/public/parallax-pagination.mov
  package.json
  src/components/Carousel.tsx
  src/components/Pagination/Basic/PaginationItem.tsx
  src/components/Pagination/Basic/index.tsx
  src/components/Pagination/index.tsx
  src/hooks/useOnProgressChange.ts
  src/index.tsx
  src/types.ts
  yarn.lock
Labels: size:XL

#574 fix: `onGestureEnd` -> `endWithSpring` uses outdated data via `useSharedValue`
  src/components/ScrollViewGesture.tsx
Labels: size:S

#591 [doc] Fix expo installation documentation
  example/website/pages/index.mdx
Labels: size:XS

#600 fix: onGestureEnd -> endWithSpring uses outdated data via useSharedValue
  .changeset/eighty-points-drum.md
  src/components/ScrollViewGesture.tsx
Labels: bug, size:S
