Repository dohooo/react-native-reanimated-carousel, pull requests merged in 2024-11, with the labels that each got.

#710 fix: dependency array; removes shared value access warning from react-native-reanimated
  .changeset/rare-insects-camp.md
  src/components/ScrollViewGesture.tsx
Labels: size:S

#716 fix: parallax layout with new arch enabled
  src/layouts/parallax.ts
Labels: size:S

#721 chore: code formatting and adds changeset
  .changeset/polite-forks-rescue.md
  src/layouts/parallax.ts
Labels: size:XS

#724 fix: next item function overscolling with overscrollEnabled is false
  .changeset/stale-grapes-cry.md
  .github/workflows/ci.yml
  .gitignore
  example/app/.gitignore
  example/app/app.json
  example/app/app/_layout.tsx
  example/app/app/demos/custom-animations/multiple/index.tsx
  example/app/package.json
  example/app/yarn.lock
  jest.config.js
  junit.xml
  package.json
  src/components/Carousel.test.tsx
  src/components/Carousel.tsx
  src/components/CarouselLayout.tsx
  src/components/ItemLayout.tsx
  src/components/ItemRenderer.tsx
  src/components/ScrollViewGesture.tsx
  src/hooks/useCarouselController.test.tsx
  src/hooks/useCarouselController.tsx
  src/hooks/useLayoutConfig.ts
  src/index.tsx
  src/store/index.ts
  src/store/index.tsx
  src/types.ts
  test/reporter.js
  tsconfig.json
  yarn.lock
Labels: size:XXL

#726 Chore/updates ci
  .github/workflows/ci.yml
Labels: size:XS

#731 fix: better slow pan: if user intent is to stay on current page, _don't_ change page
  .changeset/wise-drinks-explode.md
  biome.json
  example/app/app/demos/basic-layouts/left-align/index.tsx
  example/app/app/demos/basic-layouts/normal/index.tsx
  example/app/app/demos/basic-layouts/parallax/demo.tsx
  example/app/app/demos/basic-layouts/parallax/index.tsx
  example/app/app/demos/basic-layouts/stack/index.tsx
  src/components/Carousel.test.tsx
  src/components/ScrollViewGesture.tsx
Labels: size:L

#732 release: version packages (canary)
  .changeset/pre.json
  CHANGELOG.md
  package.json
Labels: size:XS

#733 fix: add pointerEvents: ‘box-none’ to ItemLayout
  .changeset/mean-needles-rhyme.md
  src/components/ItemLayout.tsx
Labels: size:XS

#734 release: version packages (canary)
  .changeset/pre.json
  CHANGELOG.md
  package.json
Labels: size:XS

#735 feat: add index parameter to customAnimation
  .changeset/modern-carpets-sleep.md
  src/components/Carousel.test.tsx
  src/components/ItemLayout.tsx
  src/components/ItemRenderer.tsx
  src/types.ts
Labels: size:M

#736 release: version packages (canary)
  .changeset/pre.json
  CHANGELOG.md
  package.json
Labels: size:XS
