Repository dohooo/react-native-reanimated-carousel, pull requests merged in 2024-09, with the labels that each got.

#629 fix: typescript error where MeasuredDimension can be null
  src/components/ScrollViewGesture.tsx
Labels: size:XS

#648 fix: typeof "function" onProgressChange - fixes app crash
  .changeset/nine-moose-whisper.md
  src/hooks/useOnProgressChange.ts
Labels: size:S

#576 fix: flicker when starting pan: `panOffset` value race condition
  .changeset/spotty-melons-return.md
  src/components/ScrollViewGesture.tsx
Labels: size:S, lgtm

#580 Feature/Docs: Add a explained documentation to the Ref section in Props page.
  example/website/pages/props.mdx
Labels: size:M

#534 docs: correct example app commands
  CONTRIBUTING.md
Labels: size:XS

#652 add Pagination.Custom dot animation
  example/app/src/pages/parallax/index.tsx
  src/components/Pagination/Custom/PaginationItem.tsx
  src/components/Pagination/Custom/index.tsx
  src/components/Pagination/index.tsx
Labels: size:L

#577 fix: gesture `onStart`, `onUpdate`, and `onEnd` (et al) should be worklets
  .changeset/many-ads-fry.md
  src/hooks/usePanGestureProxy.test.tsx
  src/hooks/usePanGestureProxy.ts
Labels: size:M

#536 refactor: using requestAnimationFrame instead of setTimeout to reduce frame skipping
  src/hooks/useAutoPlay.ts
Labels: size:M

#672 fix: revert autoPlay changes
  .changeset/cyan-snails-move.md
  src/hooks/useAutoPlay.ts
Labels: size:M

#674 chore: update yarn lock file
  example/website/yarn.lock
Labels: size:XS

#677 fix: PaginationItem onPress (both Pagination.Basic and Pagination.Custom)
  .changeset/cyan-pillows-swim.md
  src/components/Pagination/Basic/PaginationItem.tsx
  src/components/Pagination/Basic/index.tsx
  src/components/Pagination/Custom/PaginationItem.tsx
  src/components/Pagination/Custom/index.tsx
Labels: size:L
