Repository dohooo/react-native-reanimated-carousel, pull requests merged in 2025-02, with the labels that each got.

#775 fix: Added missing dependencies for web to work
  src/components/CarouselLayout.tsx
  src/components/ItemLayout.tsx
  src/hooks/useOffsetX.ts
Labels: size:XS

#774 fix: #684 type error `property push does not exist on type`
  src/layouts/stack.ts
Labels: size:M

#767 fix(bug): Loss of precision during arithmetic conversion
  src/layouts/stack.ts
Labels: size:XS

#777 release: version packages (canary)
  .changeset/pre.json
  CHANGELOG.md
  package.json
Labels: size:S

#778 release: version packages
  .changeset/big-ligers-nail.md
  .changeset/big-trees-begin.md
  .changeset/bright-socks-change.md
  .changeset/brown-onions-wave.md
  .changeset/clever-pants-approve.md
  .changeset/cyan-pillows-swim.md
  .changeset/cyan-snails-move.md
  .changeset/eighty-points-drum.md
  .changeset/famous-starfishes-begin.md
  .changeset/gold-onions-chew.md
  .changeset/hungry-actors-grab.md
  .changeset/lazy-ties-design.md
  .changeset/lazy-tips-wave.md
  .changeset/loud-cars-hunt.md
  .changeset/many-ads-fry.md
  .changeset/mean-needles-rhyme.md
  .changeset/mighty-pianos-pull.md
  .changeset/modern-carpets-sleep.md
  .changeset/nine-moose-whisper.md
  .changeset/polite-forks-rescue.md
  .changeset/poor-pets-eat.md
  .changeset/pre.json
  .changeset/proud-bobcats-tan.md
  .changeset/proud-zebras-jump.md
  .changeset/rare-insects-camp.md
  .changeset/short-avocados-sparkle.md
  .changeset/shy-walls-clap.md
  .changeset/slow-donkeys-rest.md
  .changeset/sour-hounds-fail.md
  .changeset/spotty-melons-return.md
  .changeset/stale-grapes-cry.md
  .changeset/stupid-points-attend.md
  .changeset/thick-ties-think.md
  .changeset/three-mangos-wait.md
  .changeset/violet-buckets-act.md
  .changeset/wise-drinks-explode.md
  .changeset/yellow-bottles-itch.md
  CHANGELOG.md
  package.json
Labels: size:L

#781 release: version packages
  .changeset/calm-ducks-play.md
  CHANGELOG.md
  package.json
Labels: size:S

#782 release: version packages
  .changeset/breezy-queens-reflect.md
  CHANGELOG.md
  package.json
Labels: size:S
